# Generated by Django 4.2.7 on 2023-11-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='last_modify_date',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='singer',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='song',
        ),
        migrations.AddField(
            model_name='accounts',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='currents',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TWD', 'TWD'), ('KRW', 'KRW'), ('JPY', 'JPY'), ('THB', 'THB')], default='TWD', max_length=3),
        ),
        migrations.AddField(
            model_name='accounts',
            name='latitude',
            field=models.FloatField(default=24.784708),
        ),
        migrations.AddField(
            model_name='accounts',
            name='longitude',
            field=models.FloatField(default=120.999058),
        ),
        migrations.AddField(
            model_name='accounts',
            name='name',
            field=models.TextField(default='default_name'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='notes',
            field=models.TextField(default='default_notes'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='payment',
            field=models.CharField(choices=[('CARD', 'Card'), ('CASH', 'Cash')], default='Cash', max_length=5),
        ),
        migrations.AddField(
            model_name='accounts',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
