# Generated by Django 4.2.7 on 2023-11-26 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('accounts', '0002_remove_accounts_last_modify_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.books'),
        ),
    ]
