# Generated by Django 4.1.13 on 2023-12-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_book_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['create_time']},
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='created',
            new_name='create_time',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='price',
        ),
        migrations.AddField(
            model_name='accounts',
            name='account_keeper',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='accounts',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='product_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='accounts',
            table=None,
        ),
    ]
