# Generated by Django 4.2.8 on 2023-12-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='book_id',
            new_name='book_belong',
        ),
    ]
