# Generated by Django 4.2.8 on 2023-12-20 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_expense_books_group_expense_and_more'),
        ('accounts', '0005_rename_book_id_accounts_book_belong'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('ENT', 'ent'), ('FOOD', 'Food'), ('TRANS', 'Trans'), ('OTHER', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='book_belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account', to='books.books'),
        ),
    ]
