# Generated by Django 4.2.8 on 2023-12-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accounts_category_alter_accounts_book_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('ENT', 'ent'), ('FOOD', 'Food'), ('TRANS', 'Trans')], default='Other', max_length=10),
        ),
    ]
