# Generated by Django 4.1.13 on 2023-12-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('OTHER', 'Other'), ('ENT', 'ent'), ('TRANS', 'Trans')], default='Other', max_length=10),
        ),
    ]
