# Generated by Django 4.1.13 on 2023-12-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('ENT', 'ent'), ('OTHER', 'Other'), ('TRANS', 'Trans'), ('FOOD', 'Food')], default='Other', max_length=10),
        ),
    ]
