# Generated by Django 4.1.13 on 2023-12-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('TRANS', 'Trans'), ('FOOD', 'Food'), ('OTHER', 'Other'), ('ENT', 'ent')], default='Other', max_length=10),
        ),
    ]
