# Generated by Django 4.2.8 on 2023-12-25 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['record_time']},
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='create_time',
        ),
        migrations.AddField(
            model_name='accounts',
            name='record_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('TRANS', 'Trans'), ('FOOD', 'Food'), ('ENT', 'ent')], default='Other', max_length=10),
        ),
    ]
