# Generated by Django 4.1.13 on 2023-12-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_accounts_options_remove_accounts_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('ENT', 'ent'), ('FOOD', 'Food'), ('TRANS', 'Trans')], default='Other', max_length=10),
        ),
    ]
