# Generated by Django 4.2.8 on 2023-12-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_accounts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
