# Generated by Django 4.2.8 on 2023-12-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_accounts_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('TRANS', 'Trans'), ('ENT', 'ent'), ('CLOTHES', 'Clothes'), ('FOOD', 'Food')], default='Other', max_length=10),
        ),
    ]
