# Generated by Django 4.1.13 on 2023-12-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_accounts_category_alter_accounts_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('FOOD', 'Food'), ('TRANS', 'Trans'), ('ENT', 'ent'), ('CLOTHES', 'Clothes')], default='OTHER', max_length=10),
        ),
    ]
