# Generated by Django 4.1.13 on 2023-12-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('CLOTHES', 'Clothes'), ('OTHER', 'Other'), ('ENT', 'ent'), ('FOOD', 'Food'), ('TRANS', 'Trans')], default='OTHER', max_length=10),
        ),
    ]
