# Generated by Django 4.1.13 on 2023-12-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRANS', 'Trans'), ('CLOTHES', 'Clothes'), ('ENT', 'ent'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
