# Generated by Django 4.1.13 on 2023-12-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('CLOTHES', 'Clothes'), ('TRANS', 'Trans'), ('ENT', 'ent'), ('FOOD', 'Food'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
