# Generated by Django 4.2.8 on 2023-12-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_accounts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='name_options',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('CLOTHES', 'Clothes'), ('ENT', 'ent'), ('TRANS', 'Trans'), ('OTHER', 'Other'), ('FOOD', 'Food')], default='OTHER', max_length=10),
        ),
    ]
