# Generated by Django 4.2.8 on 2023-12-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_accounts_name_options_alter_accounts_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='name_options',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('FOOD', 'Food'), ('CLOTHES', 'Clothes'), ('TRANS', 'Trans'), ('ENT', 'ent')], default='OTHER', max_length=10),
        ),
    ]
