# Generated by Django 4.1.13 on 2023-12-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_accounts_name_options_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('FOOD', 'Food'), ('TRANS', 'Trans'), ('ENT', 'ent'), ('CLOTHES', 'Clothes')], default='OTHER', max_length=10),
        ),
    ]
