# Generated by Django 4.1.13 on 2023-12-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('TRANS', 'Trans'), ('FOOD', 'Food'), ('OTHER', 'Other'), ('CLOTHES', 'Clothes'), ('ENT', 'ent')], default='OTHER', max_length=10),
        ),
    ]
