# Generated by Django 4.1.13 on 2023-12-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('ENT', 'ent'), ('TRANS', 'Trans'), ('CLOTHES', 'Clothes'), ('OTHER', 'Other'), ('FOOD', 'Food')], default='OTHER', max_length=10),
        ),
    ]
