# Generated by Django 4.2.8 on 2024-01-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_accounts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('TRANS', 'Trans'), ('FOOD', 'Food'), ('ENT', 'ent'), ('OTHER', 'Other'), ('CLOTHES', 'Clothes')], default='OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='payment',
            field=models.CharField(choices=[('信用卡', 'Card'), ('現金', 'Cash')], default='現金', max_length=5),
        ),
    ]
