# Generated by Django 4.2.8 on 2024-01-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_accounts_category_alter_accounts_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='category',
            field=models.CharField(choices=[('衣服', 'Clothes'), ('其他', 'Other'), ('娛樂', 'ent'), ('交通', 'Trans'), ('食物', 'Food')], default='OTHER', max_length=10),
        ),
    ]
