# Generated by Django 4.2.7 on 2023-11-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('name', models.TextField(default='default_name')),
                ('cover_img', models.ImageField(upload_to='')),
                ('budget', models.FloatField(verbose_name=10000.0)),
                ('expense', models.FloatField(verbose_name=9000.0)),
                ('notes', models.TextField(default='default_notes')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
