# Generated by Django 4.1.13 on 2023-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='books',
            name='user_email_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='budget',
            field=models.FloatField(default=10000.0),
        ),
        migrations.AlterField(
            model_name='books',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='expense',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='notes',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='books',
            table=None,
        ),
    ]
