# Generated by Django 4.1.13 on 2023-12-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_options_books_user_email_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
