# Generated by Django 4.1.13 on 2023-12-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
