# Generated by Django 4.1.13 on 2023-12-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='expense',
            new_name='group_expense',
        ),
        migrations.RemoveField(
            model_name='books',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='books',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='books',
            name='user_email_list',
        ),
    ]
