# Generated by Django 4.1.13 on 2023-12-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_expense_books_group_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
