# Generated by Django 4.2.7 on 2023-11-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('longitude', models.FloatField(default=120.999058)),
                ('latitude', models.FloatField(default=24.784708)),
                ('img_url', models.URLField()),
                ('notes', models.TextField(default='default_notes')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.books')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
    ]
