# Generated by Django 4.1.13 on 2023-12-13 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accounts_options_and_more'),
        ('books', '0005_rename_expense_books_group_expense_and_more'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['create_time']},
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='data',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='photos',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='photos',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.books'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterModelTable(
            name='photos',
            table=None,
        ),
    ]
