# Generated by Django 4.2.7 on 2023-12-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='current_book_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
    ]
