# Generated by Django 4.1.13 on 2023-12-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_book_management_user_account_management_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account_management',
            old_name='account',
            new_name='accounts',
        ),
        migrations.RenameField(
            model_name='user_account_management',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='user_book_management',
            old_name='book',
            new_name='books',
        ),
        migrations.RenameField(
            model_name='user_book_management',
            old_name='user',
            new_name='users',
        ),
    ]
