# Generated by Django 4.2.8 on 2023-12-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_account_user_account_management_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
